[package]
name = "messenger-desktop-tauri"
version = "1.0.0"
description = "Messenger desktop wrapper"
authors = ["you"]
edition = "2021"

[lib]
name = "messenger_desktop_tauri_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
panic = "abort"
strip = true
